<?php

/**
 * ExamQuestionMasterTblTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExamQuestionMasterTblTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExamQuestionMasterTblTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ExamQuestionMasterTbl');
    }
}