<?php

/**
 * ExamQuestionTypeTblTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExamQuestionTypeTblTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExamQuestionTypeTblTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ExamQuestionTypeTbl');
    }
}