<?php

/**
 * ExamPaperTemplateTblTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExamPaperTemplateTblTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExamPaperTemplateTblTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ExamPaperTemplateTbl');
    }
}