<?php

/**
 * ExamQuestionChapterTblTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExamQuestionChapterTblTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExamQuestionChapterTblTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ExamQuestionChapterTbl');
    }
}