<?php

/**
 * ExamPaperConfigTblTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExamPaperConfigTblTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExamPaperConfigTblTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ExamPaperConfigTbl');
    }
}