<?php

/**
 * ExamPaperMasterTblTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExamPaperMasterTblTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExamPaperMasterTblTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ExamPaperMasterTbl');
    }
}