<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ExamQuestionChapterTbl', 'doctrine');

/**
 * BaseExamQuestionChapterTbl
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $parent_cid
 * @property string $name
 * @property string $is_parent
 * @property Doctrine_Collection $ExamPaperConfigTbl
 * 
 * @method integer                getId()                 Returns the current record's "id" value
 * @method integer                getParentCid()          Returns the current record's "parent_cid" value
 * @method string                 getName()               Returns the current record's "name" value
 * @method string                 getIsParent()           Returns the current record's "is_parent" value
 * @method Doctrine_Collection    getExamPaperConfigTbl() Returns the current record's "ExamPaperConfigTbl" collection
 * @method ExamQuestionChapterTbl setId()                 Sets the current record's "id" value
 * @method ExamQuestionChapterTbl setParentCid()          Sets the current record's "parent_cid" value
 * @method ExamQuestionChapterTbl setName()               Sets the current record's "name" value
 * @method ExamQuestionChapterTbl setIsParent()           Sets the current record's "is_parent" value
 * @method ExamQuestionChapterTbl setExamPaperConfigTbl() Sets the current record's "ExamPaperConfigTbl" collection
 * 
 * @package    ExamPaper
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseExamQuestionChapterTbl extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('exam_question_chapter_tbl');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('parent_cid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('is_parent', 'string', 1, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ExamPaperConfigTbl', array(
             'local' => 'id',
             'foreign' => 'ep_ques_chapter_id'));
    }
}