<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ExamPaperTemplateTbl', 'doctrine');

/**
 * BaseExamPaperTemplateTbl
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $position
 * @property string $template
 * 
 * @method integer              getId()       Returns the current record's "id" value
 * @method string               getPosition() Returns the current record's "position" value
 * @method string               getTemplate() Returns the current record's "template" value
 * @method ExamPaperTemplateTbl setId()       Sets the current record's "id" value
 * @method ExamPaperTemplateTbl setPosition() Sets the current record's "position" value
 * @method ExamPaperTemplateTbl setTemplate() Sets the current record's "template" value
 * 
 * @package    ExamPaper
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseExamPaperTemplateTbl extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('exam_paper_template_tbl');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('position', 'string', 32, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => 32,
             ));
        $this->hasColumn('template', 'string', 10000, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => 10000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}