<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ExamPaperMasterTbl', 'doctrine');

/**
 * BaseExamPaperMasterTbl
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property string $ep_difficulty
 * @property integer $is_build_flag
 * @property timestamp $insert_date
 * @property timestamp $update_date
 * @property timestamp $delete_date
 * 
 * @method integer            getId()            Returns the current record's "id" value
 * @method string             getTitle()         Returns the current record's "title" value
 * @method string             getEpDifficulty()  Returns the current record's "ep_difficulty" value
 * @method integer            getIsBuildFlag()   Returns the current record's "is_build_flag" value
 * @method timestamp          getInsertDate()    Returns the current record's "insert_date" value
 * @method timestamp          getUpdateDate()    Returns the current record's "update_date" value
 * @method timestamp          getDeleteDate()    Returns the current record's "delete_date" value
 * @method ExamPaperMasterTbl setId()            Sets the current record's "id" value
 * @method ExamPaperMasterTbl setTitle()         Sets the current record's "title" value
 * @method ExamPaperMasterTbl setEpDifficulty()  Sets the current record's "ep_difficulty" value
 * @method ExamPaperMasterTbl setIsBuildFlag()   Sets the current record's "is_build_flag" value
 * @method ExamPaperMasterTbl setInsertDate()    Sets the current record's "insert_date" value
 * @method ExamPaperMasterTbl setUpdateDate()    Sets the current record's "update_date" value
 * @method ExamPaperMasterTbl setDeleteDate()    Sets the current record's "delete_date" value
 * 
 * @package    ExamPaper
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseExamPaperMasterTbl extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('exam_paper_master_tbl');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('ep_difficulty', 'string', 2, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('is_build_flag', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('insert_date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('update_date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('delete_date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}