<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ExamPaperFinalTbl', 'doctrine');

/**
 * BaseExamPaperFinalTbl
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $exam_paper_id
 * @property integer $exam_ques_type_id
 * @property integer $exam_ques_id
 * @property timestamp $insert_date
 * @property timestamp $update_date
 * @property timestamp $delete_date
 * @property ExamQuestionMasterTbl $ExamQuestionMasterTbl
 * 
 * @method integer               getId()                    Returns the current record's "id" value
 * @method integer               getExamPaperId()           Returns the current record's "exam_paper_id" value
 * @method integer               getExamQuesTypeId()        Returns the current record's "exam_ques_type_id" value
 * @method integer               getExamQuesId()            Returns the current record's "exam_ques_id" value
 * @method timestamp             getInsertDate()            Returns the current record's "insert_date" value
 * @method timestamp             getUpdateDate()            Returns the current record's "update_date" value
 * @method timestamp             getDeleteDate()            Returns the current record's "delete_date" value
 * @method ExamQuestionMasterTbl getExamQuestionMasterTbl() Returns the current record's "ExamQuestionMasterTbl" value
 * @method ExamPaperFinalTbl     setId()                    Sets the current record's "id" value
 * @method ExamPaperFinalTbl     setExamPaperId()           Sets the current record's "exam_paper_id" value
 * @method ExamPaperFinalTbl     setExamQuesTypeId()        Sets the current record's "exam_ques_type_id" value
 * @method ExamPaperFinalTbl     setExamQuesId()            Sets the current record's "exam_ques_id" value
 * @method ExamPaperFinalTbl     setInsertDate()            Sets the current record's "insert_date" value
 * @method ExamPaperFinalTbl     setUpdateDate()            Sets the current record's "update_date" value
 * @method ExamPaperFinalTbl     setDeleteDate()            Sets the current record's "delete_date" value
 * @method ExamPaperFinalTbl     setExamQuestionMasterTbl() Sets the current record's "ExamQuestionMasterTbl" value
 * 
 * @package    ExamPaper
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseExamPaperFinalTbl extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('exam_paper_final_tbl');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('exam_paper_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('exam_ques_type_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('exam_ques_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('insert_date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('update_date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('delete_date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ExamQuestionMasterTbl', array(
             'local' => 'exam_ques_id',
             'foreign' => 'id'));
    }
}