<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ExamPaperConfigTbl', 'doctrine');

/**
 * BaseExamPaperConfigTbl
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $ep_id
 * @property integer $ep_ques_type_id
 * @property integer $ep_ques_chapter_id
 * @property integer $ep_ques_number
 * @property ExamQuestionChapterTbl $ExamQuestionChapterTbl
 * @property ExamQuestionTypeTbl $ExamQuestionTypeTbl
 * 
 * @method integer                getId()                     Returns the current record's "id" value
 * @method integer                getEpId()                   Returns the current record's "ep_id" value
 * @method integer                getEpQuesTypeId()           Returns the current record's "ep_ques_type_id" value
 * @method integer                getEpQuesChapterId()        Returns the current record's "ep_ques_chapter_id" value
 * @method integer                getEpQuesNumber()           Returns the current record's "ep_ques_number" value
 * @method ExamQuestionChapterTbl getExamQuestionChapterTbl() Returns the current record's "ExamQuestionChapterTbl" value
 * @method ExamQuestionTypeTbl    getExamQuestionTypeTbl()    Returns the current record's "ExamQuestionTypeTbl" value
 * @method ExamPaperConfigTbl     setId()                     Sets the current record's "id" value
 * @method ExamPaperConfigTbl     setEpId()                   Sets the current record's "ep_id" value
 * @method ExamPaperConfigTbl     setEpQuesTypeId()           Sets the current record's "ep_ques_type_id" value
 * @method ExamPaperConfigTbl     setEpQuesChapterId()        Sets the current record's "ep_ques_chapter_id" value
 * @method ExamPaperConfigTbl     setEpQuesNumber()           Sets the current record's "ep_ques_number" value
 * @method ExamPaperConfigTbl     setExamQuestionChapterTbl() Sets the current record's "ExamQuestionChapterTbl" value
 * @method ExamPaperConfigTbl     setExamQuestionTypeTbl()    Sets the current record's "ExamQuestionTypeTbl" value
 * 
 * @package    ExamPaper
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseExamPaperConfigTbl extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('exam_paper_config_tbl');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('ep_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('ep_ques_type_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('ep_ques_chapter_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('ep_ques_number', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ExamQuestionChapterTbl', array(
             'local' => 'ep_ques_chapter_id',
             'foreign' => 'id'));

        $this->hasOne('ExamQuestionTypeTbl', array(
             'local' => 'ep_ques_type_id',
             'foreign' => 'id'));
    }
}