<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/03/28 18:38:07

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=exam_paper',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
