ExamPaperConfigTbl:
  connection: doctrine
  tableName: exam_paper_config_tbl
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    ep_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    ep_ques_type_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    ep_ques_chapter_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    ep_ques_number:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    ExamQuestionChapterTbl:
      local: ep_ques_chapter_id
      foreign: id
      type: one
    ExamQuestionTypeTbl:
      local: ep_ques_type_id
      foreign: id
      type: one
ExamPaperFinalTbl:
  connection: doctrine
  tableName: exam_paper_final_tbl
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    exam_paper_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    exam_ques_type_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    exam_ques_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    insert_date:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    update_date:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    delete_date:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    ExamQuestionMasterTbl:
      local: exam_ques_id
      foreign: id
      type: one
ExamPaperMasterTbl:
  connection: doctrine
  tableName: exam_paper_master_tbl
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    title:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    ep_difficulty:
      type: string(2)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    is_build_flag:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: false
      autoincrement: false
    insert_date:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    update_date:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    delete_date:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
ExamQuestionChapterTbl:
  connection: doctrine
  tableName: exam_question_chapter_tbl
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    parent_cid:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    name:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    is_parent:
      type: string(1)
      fixed: true
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    ExamPaperConfigTbl:
      local: id
      foreign: ep_ques_chapter_id
      type: many
ExamQuestionMasterTbl:
  connection: doctrine
  tableName: exam_question_master_tbl
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    ques_content:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    ques_type_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    ques_chapter_ids:
      type: string(64)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    ques_difficulties:
      type: string(128)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    pic_path:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    insert_date:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    update_date:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    delete_date:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    ExamQuestionTypeTbl:
      local: ques_type_id
      foreign: id
      type: one
    ExamPaperFinalTbl:
      local: id
      foreign: exam_ques_id
      type: many
ExamQuestionTypeTbl:
  connection: doctrine
  tableName: exam_question_type_tbl
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    qt_name:
      type: string(128)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    qt_abbr:
      type: string(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    sequence:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    delete_flag:
      type: string(1)
      fixed: true
      unsigned: false
      primary: false
      default: '0'
      notnull: false
      autoincrement: false
  relations:
    ExamPaperConfigTbl:
      local: id
      foreign: ep_ques_type_id
      type: many
    ExamQuestionMasterTbl:
      local: id
      foreign: ques_type_id
      type: many
      
ExamPaperTemplateTbl:
  connection: doctrine
  tableName: exam_paper_template_tbl
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    position:
      type: string(32)
      fixed: false
      unsigned: false
      primary: false
      autoincrement: false
    template:
      type: string(10000)
      fixed: false
      unsigned: false
      primary: false
      autoincrement: false


